//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdministrativeClient.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDto", Namespace="http://schemas.datacontract.org/2004/07/UserCRUDService")]
    [System.SerializableAttribute()]
    public partial class UserDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string nicknameField;
        
        private byte[] photoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string nickname {
            get {
                return this.nicknameField;
            }
            set {
                if ((object.ReferenceEquals(this.nicknameField, value) != true)) {
                    this.nicknameField = value;
                    this.RaisePropertyChanged("nickname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public byte[] photo {
            get {
                return this.photoField;
            }
            set {
                if ((object.ReferenceEquals(this.photoField, value) != true)) {
                    this.photoField = value;
                    this.RaisePropertyChanged("photo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActionResult", Namespace="http://schemas.datacontract.org/2004/07/ActionResults")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AdministrativeClient.ServiceReference.UserListActionResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AdministrativeClient.ServiceReference.ScoreListActionResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AdministrativeClient.ServiceReference.GamesStatisticsActionResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AdministrativeClient.ServiceReference.UserActionResult))]
    public partial class ActionResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string Messagek__BackingFieldField;
        
        private bool Successk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Message>k__BackingField", IsRequired=true)]
        public string Messagek__BackingField {
            get {
                return this.Messagek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Messagek__BackingFieldField, value) != true)) {
                    this.Messagek__BackingFieldField = value;
                    this.RaisePropertyChanged("Messagek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Success>k__BackingField", IsRequired=true)]
        public bool Successk__BackingField {
            get {
                return this.Successk__BackingFieldField;
            }
            set {
                if ((this.Successk__BackingFieldField.Equals(value) != true)) {
                    this.Successk__BackingFieldField = value;
                    this.RaisePropertyChanged("Successk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserListActionResult", Namespace="http://schemas.datacontract.org/2004/07/ActionResults")]
    [System.SerializableAttribute()]
    public partial class UserListActionResult : AdministrativeClient.ServiceReference.ActionResult {
        
        private AdministrativeClient.ServiceReference.UserDto[] UsersListk__BackingFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<UsersList>k__BackingField", IsRequired=true)]
        public AdministrativeClient.ServiceReference.UserDto[] UsersListk__BackingField {
            get {
                return this.UsersListk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.UsersListk__BackingFieldField, value) != true)) {
                    this.UsersListk__BackingFieldField = value;
                    this.RaisePropertyChanged("UsersListk__BackingField");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ScoreListActionResult", Namespace="http://schemas.datacontract.org/2004/07/ActionResults")]
    [System.SerializableAttribute()]
    public partial class ScoreListActionResult : AdministrativeClient.ServiceReference.ActionResult {
        
        private AdministrativeClient.ServiceReference.ScoreDto[] ScoreListk__BackingFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ScoreList>k__BackingField", IsRequired=true)]
        public AdministrativeClient.ServiceReference.ScoreDto[] ScoreListk__BackingField {
            get {
                return this.ScoreListk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ScoreListk__BackingFieldField, value) != true)) {
                    this.ScoreListk__BackingFieldField = value;
                    this.RaisePropertyChanged("ScoreListk__BackingField");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GamesStatisticsActionResult", Namespace="http://schemas.datacontract.org/2004/07/ActionResults")]
    [System.SerializableAttribute()]
    public partial class GamesStatisticsActionResult : AdministrativeClient.ServiceReference.ActionResult {
        
        private AdministrativeClient.ServiceReference.GameReportDto[] GamesStatisticsk__BackingFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<GamesStatistics>k__BackingField", IsRequired=true)]
        public AdministrativeClient.ServiceReference.GameReportDto[] GamesStatisticsk__BackingField {
            get {
                return this.GamesStatisticsk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.GamesStatisticsk__BackingFieldField, value) != true)) {
                    this.GamesStatisticsk__BackingFieldField = value;
                    this.RaisePropertyChanged("GamesStatisticsk__BackingField");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserActionResult", Namespace="http://schemas.datacontract.org/2004/07/ActionResults")]
    [System.SerializableAttribute()]
    public partial class UserActionResult : AdministrativeClient.ServiceReference.ActionResult {
        
        private AdministrativeClient.ServiceReference.UserDto Userk__BackingFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<User>k__BackingField", IsRequired=true)]
        public AdministrativeClient.ServiceReference.UserDto Userk__BackingField {
            get {
                return this.Userk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Userk__BackingFieldField, value) != true)) {
                    this.Userk__BackingFieldField = value;
                    this.RaisePropertyChanged("Userk__BackingField");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ScoreDto", Namespace="http://schemas.datacontract.org/2004/07/GamesInfoService")]
    [System.SerializableAttribute()]
    public partial class ScoreDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime Datek__BackingFieldField;
        
        private int Pointsk__BackingFieldField;
        
        private AdministrativeClient.ServiceReference.Role RolePlayedk__BackingFieldField;
        
        private string UserNicknamek__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Date>k__BackingField", IsRequired=true)]
        public System.DateTime Datek__BackingField {
            get {
                return this.Datek__BackingFieldField;
            }
            set {
                if ((this.Datek__BackingFieldField.Equals(value) != true)) {
                    this.Datek__BackingFieldField = value;
                    this.RaisePropertyChanged("Datek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Points>k__BackingField", IsRequired=true)]
        public int Pointsk__BackingField {
            get {
                return this.Pointsk__BackingFieldField;
            }
            set {
                if ((this.Pointsk__BackingFieldField.Equals(value) != true)) {
                    this.Pointsk__BackingFieldField = value;
                    this.RaisePropertyChanged("Pointsk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<RolePlayed>k__BackingField", IsRequired=true)]
        public AdministrativeClient.ServiceReference.Role RolePlayedk__BackingField {
            get {
                return this.RolePlayedk__BackingFieldField;
            }
            set {
                if ((this.RolePlayedk__BackingFieldField.Equals(value) != true)) {
                    this.RolePlayedk__BackingFieldField = value;
                    this.RaisePropertyChanged("RolePlayedk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<UserNickname>k__BackingField", IsRequired=true)]
        public string UserNicknamek__BackingField {
            get {
                return this.UserNicknamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNicknamek__BackingFieldField, value) != true)) {
                    this.UserNicknamek__BackingFieldField = value;
                    this.RaisePropertyChanged("UserNicknamek__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Role", Namespace="http://schemas.datacontract.org/2004/07/GameLogic")]
    public enum Role : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MONSTER = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SURVIVOR = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NEUTRAL = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameReportDto", Namespace="http://schemas.datacontract.org/2004/07/UserCRUDServiceContract")]
    [System.SerializableAttribute()]
    public partial class GameReportDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime Datek__BackingFieldField;
        
        private AdministrativeClient.ServiceReference.PlayerFieldDto[] PlayersReportsk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Date>k__BackingField", IsRequired=true)]
        public System.DateTime Datek__BackingField {
            get {
                return this.Datek__BackingFieldField;
            }
            set {
                if ((this.Datek__BackingFieldField.Equals(value) != true)) {
                    this.Datek__BackingFieldField = value;
                    this.RaisePropertyChanged("Datek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<PlayersReports>k__BackingField", IsRequired=true)]
        public AdministrativeClient.ServiceReference.PlayerFieldDto[] PlayersReportsk__BackingField {
            get {
                return this.PlayersReportsk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayersReportsk__BackingFieldField, value) != true)) {
                    this.PlayersReportsk__BackingFieldField = value;
                    this.RaisePropertyChanged("PlayersReportsk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerFieldDto", Namespace="http://schemas.datacontract.org/2004/07/UserCRUDServiceContract")]
    [System.SerializableAttribute()]
    public partial class PlayerFieldDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string PlayerNamek__BackingFieldField;
        
        private string RolePlayedk__BackingFieldField;
        
        private bool Wonk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<PlayerName>k__BackingField", IsRequired=true)]
        public string PlayerNamek__BackingField {
            get {
                return this.PlayerNamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayerNamek__BackingFieldField, value) != true)) {
                    this.PlayerNamek__BackingFieldField = value;
                    this.RaisePropertyChanged("PlayerNamek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<RolePlayed>k__BackingField", IsRequired=true)]
        public string RolePlayedk__BackingField {
            get {
                return this.RolePlayedk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.RolePlayedk__BackingFieldField, value) != true)) {
                    this.RolePlayedk__BackingFieldField = value;
                    this.RaisePropertyChanged("RolePlayedk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Won>k__BackingField", IsRequired=true)]
        public bool Wonk__BackingField {
            get {
                return this.Wonk__BackingFieldField;
            }
            set {
                if ((this.Wonk__BackingFieldField.Equals(value) != true)) {
                    this.Wonk__BackingFieldField = value;
                    this.RaisePropertyChanged("Wonk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IWebService")]
    public interface IWebService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/AddUser", ReplyAction="http://tempuri.org/IWebService/AddUserResponse")]
        string AddUser(AdministrativeClient.ServiceReference.UserDto user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/AddUser", ReplyAction="http://tempuri.org/IWebService/AddUserResponse")]
        System.Threading.Tasks.Task<string> AddUserAsync(AdministrativeClient.ServiceReference.UserDto user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/DeleteUser", ReplyAction="http://tempuri.org/IWebService/DeleteUserResponse")]
        string DeleteUser(string nickname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/DeleteUser", ReplyAction="http://tempuri.org/IWebService/DeleteUserResponse")]
        System.Threading.Tasks.Task<string> DeleteUserAsync(string nickname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/ModifyUser", ReplyAction="http://tempuri.org/IWebService/ModifyUserResponse")]
        string ModifyUser(string oldNickname, AdministrativeClient.ServiceReference.UserDto modified);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/ModifyUser", ReplyAction="http://tempuri.org/IWebService/ModifyUserResponse")]
        System.Threading.Tasks.Task<string> ModifyUserAsync(string oldNickname, AdministrativeClient.ServiceReference.UserDto modified);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/Get", ReplyAction="http://tempuri.org/IWebService/GetResponse")]
        AdministrativeClient.ServiceReference.UserActionResult Get(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/Get", ReplyAction="http://tempuri.org/IWebService/GetResponse")]
        System.Threading.Tasks.Task<AdministrativeClient.ServiceReference.UserActionResult> GetAsync(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetAllUsers", ReplyAction="http://tempuri.org/IWebService/GetAllUsersResponse")]
        AdministrativeClient.ServiceReference.UserListActionResult GetAllUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetAllUsers", ReplyAction="http://tempuri.org/IWebService/GetAllUsersResponse")]
        System.Threading.Tasks.Task<AdministrativeClient.ServiceReference.UserListActionResult> GetAllUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetTopScores", ReplyAction="http://tempuri.org/IWebService/GetTopScoresResponse")]
        AdministrativeClient.ServiceReference.ScoreListActionResult GetTopScores();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetTopScores", ReplyAction="http://tempuri.org/IWebService/GetTopScoresResponse")]
        System.Threading.Tasks.Task<AdministrativeClient.ServiceReference.ScoreListActionResult> GetTopScoresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetLastGamesStatistics", ReplyAction="http://tempuri.org/IWebService/GetLastGamesStatisticsResponse")]
        AdministrativeClient.ServiceReference.GamesStatisticsActionResult GetLastGamesStatistics();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetLastGamesStatistics", ReplyAction="http://tempuri.org/IWebService/GetLastGamesStatisticsResponse")]
        System.Threading.Tasks.Task<AdministrativeClient.ServiceReference.GamesStatisticsActionResult> GetLastGamesStatisticsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetLastMatchLog", ReplyAction="http://tempuri.org/IWebService/GetLastMatchLogResponse")]
        string GetLastMatchLog();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebService/GetLastMatchLog", ReplyAction="http://tempuri.org/IWebService/GetLastMatchLogResponse")]
        System.Threading.Tasks.Task<string> GetLastMatchLogAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWebServiceChannel : AdministrativeClient.ServiceReference.IWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceClient : System.ServiceModel.ClientBase<AdministrativeClient.ServiceReference.IWebService>, AdministrativeClient.ServiceReference.IWebService {
        
        public WebServiceClient() {
        }
        
        public WebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string AddUser(AdministrativeClient.ServiceReference.UserDto user) {
            return base.Channel.AddUser(user);
        }
        
        public System.Threading.Tasks.Task<string> AddUserAsync(AdministrativeClient.ServiceReference.UserDto user) {
            return base.Channel.AddUserAsync(user);
        }
        
        public string DeleteUser(string nickname) {
            return base.Channel.DeleteUser(nickname);
        }
        
        public System.Threading.Tasks.Task<string> DeleteUserAsync(string nickname) {
            return base.Channel.DeleteUserAsync(nickname);
        }
        
        public string ModifyUser(string oldNickname, AdministrativeClient.ServiceReference.UserDto modified) {
            return base.Channel.ModifyUser(oldNickname, modified);
        }
        
        public System.Threading.Tasks.Task<string> ModifyUserAsync(string oldNickname, AdministrativeClient.ServiceReference.UserDto modified) {
            return base.Channel.ModifyUserAsync(oldNickname, modified);
        }
        
        public AdministrativeClient.ServiceReference.UserActionResult Get(string userName) {
            return base.Channel.Get(userName);
        }
        
        public System.Threading.Tasks.Task<AdministrativeClient.ServiceReference.UserActionResult> GetAsync(string userName) {
            return base.Channel.GetAsync(userName);
        }
        
        public AdministrativeClient.ServiceReference.UserListActionResult GetAllUsers() {
            return base.Channel.GetAllUsers();
        }
        
        public System.Threading.Tasks.Task<AdministrativeClient.ServiceReference.UserListActionResult> GetAllUsersAsync() {
            return base.Channel.GetAllUsersAsync();
        }
        
        public AdministrativeClient.ServiceReference.ScoreListActionResult GetTopScores() {
            return base.Channel.GetTopScores();
        }
        
        public System.Threading.Tasks.Task<AdministrativeClient.ServiceReference.ScoreListActionResult> GetTopScoresAsync() {
            return base.Channel.GetTopScoresAsync();
        }
        
        public AdministrativeClient.ServiceReference.GamesStatisticsActionResult GetLastGamesStatistics() {
            return base.Channel.GetLastGamesStatistics();
        }
        
        public System.Threading.Tasks.Task<AdministrativeClient.ServiceReference.GamesStatisticsActionResult> GetLastGamesStatisticsAsync() {
            return base.Channel.GetLastGamesStatisticsAsync();
        }
        
        public string GetLastMatchLog() {
            return base.Channel.GetLastMatchLog();
        }
        
        public System.Threading.Tasks.Task<string> GetLastMatchLogAsync() {
            return base.Channel.GetLastMatchLogAsync();
        }
    }
}
